# Favorita: Favorita Grocery Sales Forecasting

## Data exploration

In [4]:
# Import libraries necessary for this project
import os.path
import pickle
import numpy as np
import pandas as pd
from sklearn.model_selection import ShuffleSplit
from IPython.display import display
import matplotlib.pyplot as plt

# Import supplementary visualizations code visuals.py
#import visuals as vs

# Pretty display for notebooks
%matplotlib inline

Training data:

In [5]:
# Load the training dataset
if not os.path.isfile('train1.pkl'):
    train_data = pd.read_csv('input/train.csv')
    print("Training dataset has {} data points with {} variables each.".format(*train_data.shape))
    one_third_index = int(train_data.shape[0] // 3)
    two_third_index = int(train_data.shape[0] * 2 // 3)
    #pickle can only dump a file with maximum size 2GB, so the train.cvs (5GB) is saved into 3 files
    pickle.dump(train_data.iloc[:one_third_index, :], open( "train1.pkl", "wb" ))
    pickle.dump(train_data.iloc[one_third_index:two_third_index, :], open( "train2.pkl", "wb" ))
    pickle.dump(train_data.iloc[two_third_index:, :], open( "train3.pkl", "wb" ))
else:
    train_data = pickle.load(open( "train1.pkl", "rb" ))
display(train_data.head(n=10))

   id        date  store_nbr  item_nbr  unit_sales onpromotion
0   0  2013-01-01         25    103665         7.0         NaN
1   1  2013-01-01         25    105574         1.0         NaN
2   2  2013-01-01         25    105575         2.0         NaN
3   3  2013-01-01         25    108079         1.0         NaN
4   4  2013-01-01         25    108701         1.0         NaN
5   5  2013-01-01         25    108786         3.0         NaN
6   6  2013-01-01         25    108797         1.0         NaN
7   7  2013-01-01         25    108952         1.0         NaN
8   8  2013-01-01         25    111397        13.0         NaN
9   9  2013-01-01         25    114790         3.0         NaN